Add missing Fl_Tile_resize
While i was trying to get fltkhs work in GHCi, i got stuck with undefined reference to Fl_Tile_resize function. It turns out that function is nowhere defined, but its imported in Tile.chs.

Weirdly only GHCi complained about missing symbol while GHC worked fine without that symbol.